
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: myapp
spec:
  replicas: 10 # number of pods to be created
  selector: # to select the pods created by this deployment
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
        ports:
        - containerPort: 80
